# General parameters
dataset: mnist_small
expid: mnist_small_run
mode: scala
seed: 9
numClasses: 10

# CKM Parameters
layers: 1
patch_sizes: [5]
bandwidth: [1]
pool: [2]
poolStride: [2]
filters: [128]
whitenerValue: 0.01
whitenerOffset: 0.1
fastfood: False 

# Solver Params
solve: True
saveFeatures: False
solver: BlockWeightedLeastSquares
kernelGamma: 5e-8
reg: 0
solverWeight: 0
blockSize: 512
numBlocks: 20
numIters: 1
whiten: True

