# General parameters
dataset: cifar
expid: cifar_run
mode: scala
seed: 12
numClasses: 10

# CKM Parameters
layers: 1
patch_sizes: [5]
bandwidth: [1.2]
pool: [14]
poolStride: [13]
filters: [4096]
whitenerValue: 0.01
whitenerOffset: 0.1

# Solver Params
solve: True
saveFeatures: True
loss: WeightedLeastSquares
reg: 0
yarn: True
solverWeight: 0
blockSize: 4096
numBlocks: 20
numIters: 1
whiten: True

