# General parameters
dataset:  sample_CHIPSEQ
expid: CHIPSEQ_small
mode: scala
seed: 0
numClasses: 2
dimensions: 1

# CKM Parameters
layers: 1
patch_sizes: [5, 1]
bandwidth: [1.8, 2.6] # gaussian parameters: compute median of L2 distance between all patches in dataset
filters: [10] # filter for layer 1, 2, incrementally increase filter size

# Solver Params
solve: true
loss: softmax
reg: 0.001
saveFeatures: true
yarn: True
cluster: false
